### ISSUE TITLE
brave appimage is broken

### ISSUE THREAD

**Issue by hcsubser** [srevinsaju/Brave-AppImage#2] opened 2021-04-08 14:38 UTC
/tmp/.mount_Brave-USh1Bq
/tmp/.mount_Brave-USh1Bq/AppRun: line 46: /tmp/.mount_Brave-USh1Bq/brave-browser: No such file or directory

it seems that something changed with how upstream packages their brave releases, which broke these scripts

**Comment by srevinsaju** [comment] 2021-04-08 14:39
Agreed, let me investigate

**Comment by AbhayF8** [comment] 2021-04-16 15:43
To fix this I extracted the appimage using
`brave*.appimage --appimage-extract`

And after extracting I went into the squashfs-root folder and I was able to run Brave by doubling clicking on brave.
On investigating, I found that the problem is with the name of this brave file. It should be brave-browser. I renamed it and packed it using appimage-appimage and now it works

Please fix this asap

**Comment by srevinsaju** [comment] 2021-04-16 15:53
@AbhayF8 Thanks for the information. I have added a fix https://github.com/srevinsaju/Brave-AppImage/commit/c0739fa947a619f95e8a4b43ab9472e577ec2f0e, the appimage should be rebuilt in 5 mins. Can you update your appimage and test it when its release?

**Comment by srevinsaju** [comment] 2021-04-16 16:23
@hcsubser @AbhayF8 I hope its fixed now: https://github.com/srevinsaju/Brave-AppImage/releases/tag/v1.23.71

**Comment by srevinsaju** [comment] 2021-04-16 16:24
Feel free to reopen, or create another issue if its still broken :smile:

**Closed as completed by srevinsaju** 2021-04-16 16:23 UTC
